apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - port: 8098
      targetPort: 8080
      nodePort: 30556
      protocol: TCP
  selector:
    app: jenkins
